apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bunny
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bunny
  source:
    path: charts/hutch
    repoURL: https://github.com/Health-Informatics-UoN/hutch.git
    targetRevision: HEAD
    helm:
      values: |
        relay:
          enabled: true

          upstreamTaskApi:
            basicAuth:
              username: "CHANGEME"
              password: "CHANGEME"
            baseUrl: "https://CHANGEME"
            collectionId: "RQ-CC-CHANGEME"

        rabbitmq:
          # Enables the rabbitmq templates
          enabled: true
          auth:
            username: "CHANGEME"
            password: "CHANGEME"

        postgresql:
          enabled: true
          auth:
            username: "CHANGEME"
            password: "CHANGEME"
        
        bunny:
          enabled: true
          extraEnvVars:
            # COLLECTION_ID is created in the Relay instance when creating a user.
            - name: COLLECTION_ID
              value: 0194cbaa-5b5f-7d86-815b-aad2ee2224fc
          taskApi:
            basicAuth:
              # Username is created in the Relay instance when creating a user.
              username: test-user-1
              # Password is created in the Relay instance when creating a user.
              password: "BdRoQP2z#sXsM79*"
          db:
            # Change to whatever the schema is in the postgresql database.
            schema: omop            

  destination:
    server: https://kubernetes.default.svc
    namespace: bunny
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
    - CreateNamespace=true 
