apiVersion: v1
kind: Secret
metadata:
  name: argocd-helm-oci-bitnami
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "true"
  name: "bitnami"
  type: helm
  url: registry-1.docker.io/bitnamicharts
#  proxy: "http://192.168.10.15:8080"