apiVersion: v1
kind: Secret
metadata:
  name: argocd-helm-hutch
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "false"
  name: "hutch"
  type: helm
  url: https://github.com/Health-Informatics-UoN/hutch.git
#  proxy: "http://192.168.10.15:8080"